### ISSUE TITLE
Toast on startup

### ISSUE THREAD

**Issue by F43nd1r** [TrianguloY/LLScript_Repository_Importer#5]
Webviewer, line 440f: Toast is shown on first run after install. (No idea how to fix)

**Comment by TrianguloY** [comment]
In fIact that toast is run when there is no saved sharedpref. So in fact the app can't know if the repository was updated or not!
Fix: remove that toast (easy right? :)

**Comment by F43nd1r** [comment]
That is not correct. The Toast should be shown if there is a repository hash, but no set.
